apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-alertmanager
  labels:
    alertmanagerConfig: my-alertmanager
spec:
  route:
    receiver: slack-receiver
    groupBy: ['job']
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 30m
  receivers:
  - name: slack-receiver
    slackConfigs:
    - channel: '#kay-local-test'
      apiURL: 
        name: my-alertmanager-slack-webhook
        key: slack-webhook
      sendResolved: true    
